[build]
  command = ""
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "https://www.easyeng.club/*"
  to = "https://easyeng.club/:splat"
  status = 301
  force = true
